config/routes.rb
TheHoarders::Application.routes.draw do

  resources :galleries
  resources :characters
  resources :contributors do
    collection do
      get "crew"
      get "actors"
    end
  end

  root :to=>"welcome#index"

end

app/models/character.rb
class Character < ActiveRecord::Base
  belongs_to :played_by, :class_name => "Contributor"
end

app/models/contributor.rb
class Contributor < ActiveRecord::Base
  belongs_to :character
end

app/models/gallery.rb
class Gallery < ActiveRecord::Base
  has_many :images
end

app/models/image.rb
class Image < ActiveRecord::Base
  belongs_to :gallery
end

app/models/page.rb
class Page < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/characters_controller.rb
class CharactersController < ApplicationController

  def index
    @characters = Character.all

    respond_to do |format|
      format.html
    end
  end

  def show

  end
  
end

app/controllers/contributors_controller.rb
class ContributorsController < ApplicationController

  def actors
    @actors = Contributor.where(:profile=>true).where("character_id is not null")

    respond_to do |format|
      format.html
    end
  end

  def crew
    @crew = Contributor.where("character_id is null").where(:profile=>true).where(:crew=>true)

    respond_to do |format|
      format.html
    end
  end
end

app/controllers/galleries_controller.rb
class GalleriesController < ApplicationController

  def index
    @galleries = Gallery.all

    respond_to do |format|
      format.html
    end
  end

  def show
    @gallery = Gallery.find(params[:id])

    respond_to do |format|
      format.html
    end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
    mentions = Twitter::Search.new
    @mentions = mentions.references("TheHoardersFilm").result_type("recent").per_page(10)

    @news = Twitter.user_timeline("TheHoardersFilm")

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/characters/index.html.haml
#characters.page
  %h2 Characters
  - @characters.each do |character|
    %h3.character #{character.name}
    =character.bio

= link_to "< Home", root_path, :class=>"home"

app/views/contributors/crew.html.haml
#crew.page
  %h2 Crew
  - @crew.each do |member|
    .member #{member.name} - #{member.position}

= link_to "< Home", root_path, :class=>"home"

app/views/galleries/index.html.haml
#galleries
  %h2 Galleries
  - @galleries.each do |gallery|
    -if gallery.images.count > 0
      .gallery=gallery.name

= link_to "< Home", root_path, :class=>"home"

app/views/galleries/show.html.haml
#galleries.page
  %h2=@gallery.name
  #lb
    -@gallery.images.each do |i|
      %a.image
        %img{:src=>i.url}
        .abstract=i.abstract

= link_to "< Home", root_path, :class=>"home"
:javascript
  dojo.require("dojox.image.Lightbox");

  

app/views/layouts/application.html.haml
%html
  %head
    %title The Hoarders - film
    =stylesheet_link_tag :all
    =javascript_include_tag "http://o.aolcdn.com/dojo/1.5/dojo/dojo.xd.js", :djConfig=>"isDebug: false, baseUrl: '/', modulePaths: { 'ab': 'javascripts/ab'}"
  %body
    #page
      .inner
        %h1 The Hoarders
        =yield

app/views/layouts/inthebox.html.haml
%html
  %head
    %title The Hoarders - film
    =stylesheet_link_tag :all
    =javascript_src_tag :src=>"http://o.aolcdn.com/dojo/1.5/dojo/dojo.xd.js"
  %body
    #page
      .inner
        %h1 The Hoarders
        =yield

app/views/welcome/index.html.haml
.rightblock
  %h3 News
  #messages
    #mentions
      - @mentions.each do |r|
        .mention #{r.from_user} said: #{r.text}

    #news
      - @news.each do |n|
        .news #{n.text}
.thebox
  %img.peek{:src=>"/images/peekinside.png"}
  #menu.menu{:style=>"display:none;"}
    %a= link_to "Gallery", galleries_path
    %a= link_to "Characters", characters_path
    %a= link_to "Concept Art", gallery_path(1)
    %a= link_to "Crew", crew_contributors_path
    .close [x] close
  :javascript
    var menu = dojo.query("#menu")[0];
    var close = dojo.query(".close")[0];

    dojo.query(".peek").forEach(function (o) {
      dojo.connect(o,"onmouseover",function (e) {
        dojo.style(menu,"display","inline-block");
      });
    });

    dojo.connect(close,"onclick",function (e) {
      dojo.style(menu,"display","none");
    });